#!/usr/bin/env python3
"""gradlecfg.py -- the bits of an Android app module's build.gradle that the javac compile check needs.

  gradlecfg.py <app/build.gradle> <gen-root>
      Writes one stand-in BuildConfig.java per product flavor to
      <gen-root>/<flavor>/<namespace-path>/BuildConfig.java (flavor "default" when the
      module has none) and prints shell assignments:
        NAMESPACE=...  VERSION_NAME=...  VERSION_CODE=...  FLAVORS="..."  RES_STRINGS="..."

  gradlecfg.py --deps <app/build.gradle>
      Prints the compile-time dependency coordinates (implementation / api / compileOnly
      lines of the form 'group:artifact:version'), one per line, for setup.sh.

Groovy is only pattern-matched, not evaluated: good enough for the usual
`key "value"` / `key = value` style, and every value is only a stand-in (the real
build's values do not matter for compiling).
"""
import os
import re
import sys


def strip_comments(src):
    src = re.sub(r"/\*.*?\*/", "", src, flags=re.S)
    return re.sub(r"//[^\n]*", "", src)


def main():
    args = sys.argv[1:]
    if len(args) == 2 and args[0] == "--deps":
        src = strip_comments(open(args[1], encoding="utf-8", errors="replace").read())
        seen = []
        for m in re.finditer(r"^\s*(implementation|api|compileOnly)\s*\(?\s*['\"]([\w.-]+:[\w.-]+:[^'\"\s]+)['\"]", src, re.M):
            if m.group(2) not in seen:
                seen.append(m.group(2))
        print("\n".join(seen))
        return
    if len(args) != 2:
        sys.stderr.write(__doc__)
        sys.exit(64)
    path, gen_root = args
    src = strip_comments(open(path, encoding="utf-8", errors="replace").read())

    def find(pattern, default):
        m = re.search(pattern, src)
        return m.group(1) if m else default

    namespace = find(r"\bnamespace\s*=?\s*['\"]([\w.]+)['\"]", "com.limelight")
    version_name = find(r"\bversionName\s*=?\s*['\"]([^'\"]*)['\"]", "0")
    version_code = find(r"\bversionCode\s*=?\s*(\d+)", "0")

    # Walk the file with a stack of enclosing block names (android / defaultConfig /
    # productFlavors / root / buildTypes / release ...).
    stack = []
    lines = []  # (stack snapshot, line text)
    for line in src.split("\n"):
        lines.append((list(stack), line))
        for m in re.finditer(r"(\w+)?\s*\{|\}", line):
            if m.group(0).endswith("{"):
                stack.append(m.group(1) or "?")
            elif stack:
                stack.pop()

    flavors = []
    app_ids = {}
    bcf = []  # (stack, type, name, value)
    release_suffix = ""
    default_app_id = None
    for st, line in lines:
        m = re.match(r"\s*(\w+)\s*\{", line)
        if m and st and st[-1] == "productFlavors" and m.group(1) not in flavors:
            flavors.append(m.group(1))
        m = re.search(r"\bapplicationId\s*=?\s*['\"]([\w.]+)['\"]", line)
        if m:
            if "productFlavors" in st and len(st) > st.index("productFlavors") + 1:
                app_ids[st[st.index("productFlavors") + 1]] = m.group(1)
            elif "defaultConfig" in st:
                default_app_id = m.group(1)
        m = re.search(r"\bapplicationIdSuffix\s*=?\s*['\"]([\w.]+)['\"]", line)
        if m and "release" in st:
            release_suffix = m.group(1)
        m = re.search(r"\bbuildConfigField\s*\(?\s*['\"]([^'\"]+)['\"]\s*,\s*['\"](\w+)['\"]\s*,\s*(.+?)\)?\s*$", line)
        if m:
            bcf.append((st, m.group(1), m.group(2), groovy_literal(m.group(3).strip())))

    res_strings = sorted(set(re.findall(r"\bresValue\s*\(?\s*['\"]string['\"]\s*,\s*['\"]([\w.]+)['\"]", src)))

    if not flavors:
        flavors = ["default"]

    for flavor in flavors:
        app_id = app_ids.get(flavor) or default_app_id or namespace
        fields = {}
        for st, typ, name, value in bcf:
            other_flavor = any(f in st for f in flavors if f != flavor)
            if flavor in st:
                score = 3
            elif other_flavor:
                continue
            elif "debug" in st:
                score = 0
            else:
                score = 2  # defaultConfig / release / top level
            if name not in fields or fields[name][0] < score:
                fields[name] = (score, typ, value)
        body = [
            "/* Generated by compilecheck (tools/compilecheck/gradlecfg.py): stand-in for AGP's BuildConfig, release build type. */",
            "package %s;" % namespace,
            "",
            "public final class BuildConfig {",
            "    public static final boolean DEBUG = false;",
            '    public static final String APPLICATION_ID = "%s";' % (app_id + release_suffix),
            '    public static final String BUILD_TYPE = "release";',
            '    public static final String FLAVOR = "%s";' % ("" if flavor == "default" else flavor),
            "    public static final int VERSION_CODE = %s;" % version_code,
            '    public static final String VERSION_NAME = "%s";' % version_name,
        ]
        for name in sorted(fields):
            score, typ, value = fields[name]
            body.append("    public static final %s %s = %s;" % (typ, name, value))
        body.append("}")
        out_dir = os.path.join(gen_root, flavor, *namespace.split("."))
        os.makedirs(out_dir, exist_ok=True)
        with open(os.path.join(out_dir, "BuildConfig.java"), "w", encoding="utf-8") as f:
            f.write("\n".join(body) + "\n")

    print("NAMESPACE=%s" % namespace)
    print("VERSION_NAME=%s" % shell_quote(version_name))
    print("VERSION_CODE=%s" % version_code)
    print('FLAVORS="%s"' % " ".join(flavors))
    print('RES_STRINGS="%s"' % " ".join(res_strings))


def groovy_literal(tok):
    """Turn the Groovy expression that holds a buildConfigField value into Java source."""
    if len(tok) >= 2 and tok[0] == '"' and tok[-1] == '"':
        return tok[1:-1].replace('\\"', '"').replace("\\\\", "\\")
    if len(tok) >= 2 and tok[0] == "'" and tok[-1] == "'":
        return tok[1:-1]
    return tok


def shell_quote(s):
    return "'" + s.replace("'", "'\\''") + "'"


if __name__ == "__main__":
    main()
